let allProducts = [
    {
        id: 1,
        title: "Sicilian Pizza",
        image: "images/1.png",
        price: 28,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 2,
        title: "Oporto Bondi Burger",
        image: "images/2.png",
        price: 22,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 3,
        title: "Vegetable Pizza",
        image: "images/3.png",
        price: 17,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 4,
        title: "Chicken Burger King",
        image: "images/4.png",
        price: 30,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 5,
        title: "Mega Meat Pizza",
        image: "images/5.png",
        price: 38,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 6,
        title: "Potato Pizza",
        image: "images/6.png",
        price: 12,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 7,
        title: "Buffalo Chicken Pizza",
        image: "images/7.png",
        price: 50,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 8,
        title: "Double Chicken Burger",
        image: "images/8.png",
        price: 30,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 9,
        title: "Crispy Chicken Burger",
        image: "images/9.png",
        price: 20,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 10,
        title: "Chicken Pepperoni Pizza",
        image: "images/10.png",
        price: 45,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 11,
        title: "Smokey Hand Burger",
        image: "images/11.png",
        price: 32,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 12,
        title: "Burger King",
        image: "images/12.png",
        price: 35,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 13,
        title: "Chicken Nuggets Burger",
        image: "images/13.png",
        price: 20,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 14,
        title: "PeriPeri Chicken Pizza",
        image: "images/14.png",
        price: 27,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 15,
        title: "Jalapeno Chicken Burger",
        image: "images/15.png",
        price: 30,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 16,
        title: "Hut Veggie Pizza",
        image: "images/16.png",
        price: 28,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 17,
        title: "Veggie Lovers Pizza",
        image: "images/17.png",
        price: 25,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 18,
        title: "Salad Burger",
        image: "images/18.png",
        price: 15,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 19,
        title: "Pie Wood Fired Pizza",
        image: "images/19.png",
        price: 19,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 20,
        title: "Giant Pink Pig Pizza",
        image: "images/20.png",
        price: 42,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 21,
        title: "Quadruple Cheeseburger",
        image: "images/21.png",
        price: 40,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 22,
        title: "Meat Festa Pizza",
        image: "images/22.png",
        price: 25,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 23,
        title: "Barbecue Chicken Pizza",
        image: "images/23.png",
        price: 22,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 24,
        title: "Hamburger",
        image: "images/24.png",
        price: 13,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
    {
        id: 25,
        title: "Caesars Cheese Pizza",
        image: "images/25.png",
        price: 20,
        count: 1,
        isInterest: false,
        category: "Pizza",
    },
    {
        id: 26,
        title: "Chicken Tender",
        image: "images/26.png",
        price: 15,
        count: 1,
        isInterest: false,
        category: "Burger",
    },
];

export default allProducts;
